### ISSUE TITLE
genomic_interpretation.interpretation_status

### ISSUE THREAD

**Issue by graefea** [BIH-CEI/ERKER2Phenopackets#102]
interpretation-status ist not transferred to phenopackets - do not know how to use interpretation_status

**Comment by frehburg** [comment]
Can confirm error message when trying to pass `interpretation_status='BLA'`

![image](https://github.com/BIH-CEI/ERKER2Phenopackets/assets/43171336/7fe1de2f-6186-4f89-ba75-3607d9bcaa48)

**Comment by frehburg** [comment]
If interpretation_status is initialized as `UNKNOWN_STATUS` the field is not displayed in the resulting phenopacket.

**Comment by frehburg** [comment]
Will still merge since added the status to config and made parameter of interpretation mapping function
