### ISSUE TITLE
HGVS String in parentheses

### ISSUE THREAD

**Issue by frehburg** [BIH-CEI/ERKER2Phenopackets#152]
> There is a small issue in the protein HGVS string.
> The [HGVS Protein recommendation](https://varnomen.hgvs.org/recommendations/protein/variant/substitution/) prescribes putting predicted consequences into parentheses:
> 
> predicted consequences, i.e. without experimental evidence (no RNA or protein sequence analysed), should be given in parentheses, e.g. p.(Arg727Ser)
> 
> Correct me if I'm wrong, but the protein effects are predicted in your data (the protein variants were not determined experimentally, e.g. with proteomic methods). Therefore, you should use
> 
> NP_005903.2:p.(Ile251Leu)
> for the example above as well as (probably) for the other phenopackets.

**Comment by graefea** [comment]
Dear @ielis ,

thank you for the comment regarding the correct p.HGVS expression. I have adjusted the original data itself so that the p.HGVS are now encoded correctly. 
Thank you!
