### ISSUE TITLE
Map Disease Block

### ISSUE THREAD

**Issue by frehburg** [BIH-CEI/ERKER2Phenopackets#62]
- [x] OMIM
- [x] ORPHA
- [x] date of diagnosis

**Comment by frehburg** [comment]
@graefea bitte einmal pullen und ueberpruefen und drueber lesen. ich weiss nicht ob ich das richtig gemacht hab. ich weiss auch nicht ganz was omim eig ist

**Comment by graefea** [comment]
ich habs hinzugefügt, OMIM gibt im Grunde nochmal den Subtyp der Krankheit wieder auf Basis der verschiendenen Mutationen. Ich habs jetzt mit dem generellen label von OMIM gefüllt und dazu haben wir dann die verschiedenen OMIM codes für die subtypen, die sich allerdings sowieso aus den HGVS Mutationen ergeben (vgl.:https://www.omim.org/allelicVariants/155541 )

**Comment by frehburg** [comment]
Muss da auch noch dieses label hin? 
![image](https://github.com/BIH-CEI/ERKER2Phenopackets/assets/43171336/70b9a1c3-4d24-48af-9a1a-f574564da5dd)
