### ISSUE TITLE
Map GeneDescriptor

### ISSUE THREAD

**Issue by frehburg** [BIH-CEI/ERKER2Phenopackets#64]
- [ ] HGNC

**Comment by frehburg** [comment]
bei GeneDescriptor ([Doc](https://phenopacket-schema.readthedocs.io/en/latest/gene.html?highlight=GeneDescriptor)) ist symbol required, aber ich glaube wir haben das nicht geparsed. Bitte ueberpruefen @graefea

**Comment by graefea** [comment]
gene symbol: bei uns immer "MC4R", also könnten wir einfach so hinzufügen, oder?
