### ISSUE TITLE
Fragen an Daniel

### ISSUE THREAD

**Issue by frehburg** [BIH-CEI/ERKER2Phenopackets#83]

**Comment by frehburg** [comment]
How should we define a TimeElement (https://phenopacket-schema.readthedocs.io/en/latest/time-element.html#rsttimeelement)
![image](https://github.com/BIH-CEI/ERKER2Phenopackets/assets/43171336/f1cc272f-e83c-4828-a57f-4887601e876e)
MapMC4R

**Comment by graefea** [comment]
How do we fill in the field 'id' in Variation Descriptor ( https://phenopacket-schema.readthedocs.io/en/latest/variant.html?highlight=variation%20descriptor) ?

**Comment by frehburg** [comment]
When defining a phenopacket, should we use this name:
![image](https://github.com/BIH-CEI/ERKER2Phenopackets/assets/43171336/e197f45f-0412-4baf-9bbe-68dde88ac43e)
or this one
![image](https://github.com/BIH-CEI/ERKER2Phenopackets/assets/43171336/0ba5bcd3-7e89-4d2d-818f-ee0af5a86f6b)

**Comment by graefea** [comment]
is vrs_ref_allele_seq corresponding to the reference genome, e.g.: GRCh38 (hg38)? 
https://phenopacket-schema.readthedocs.io/en/latest/variant.html?highlight=variation%20descriptor

**Comment by frehburg** [comment]
> How do we fill in the field 'id' in Variation Descriptor ( https://phenopacket-schema.readthedocs.io/en/latest/variant.html?highlight=variation%20descriptor) ?

just needs to be unique in phenopacket

**Comment by frehburg** [comment]
![image](https://github.com/BIH-CEI/ERKER2Phenopackets/assets/43171336/f5f03025-4a0f-4122-83bd-12e763188291)
 where phenopacket doc

**Comment by frehburg** [comment]
thejacksonlaboratory/hpo-tolkit
