### ISSUE TITLE
store ref allele in vcf record

### ISSUE THREAD

**Issue by frehburg** [BIH-CEI/ERKER2Phenopackets#92]

**Comment by graefea** [comment]
Based on HGVS format (https://varnomen.hgvs.org/bg-material/simple/) the ref allel is already given in the names themselves. To fill VcfRecord in VariationDescriptor data elements of MC4R would be missing (https://phenopacket-schema.readthedocs.io/en/latest/variant.html?highlight=ref%20allel#vcf).
